name: gha_indie_worker_flutter
description: Flutter client for GHA Indie Worker
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  gha_indie_worker_client:
    git:
      url: https://github.com/gha-indie-worker/gha-indie-worker-clients.git
      path: clients/dart
      ref: 8c7ea1ed846724330062068935793c71d0e0cff5
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
